restrictions:
 - making sure you're in bed by 10:00PM 
 - not purchasing fast-food 

boundaries: 
 - having clear expectations in all professional relationships
 - keeping conversation with relatives purposeful

relapse: 
 - not staying at home all day

accountability:
 - not letting people get under your skin
 - not isolating 
