values: 
  - Truth
  - Courage
  - Innovation
  - Nature

daily: 
  - Exercise 
  - Writing 
  - Creating
  - Advancing Professionally
  - Learning 
  - Communing with Nature

fellowship:
  - Sports
  - Video Games 
  - Tech/Engineering
  - Volunteering

accomplishments:
  - accepted the end of a relationship without anger 
  - Got myself help when I knew I needed it