desires:
 - be clear and sharp between the ears
 - lead healthy change in my family
 - have a strong body, strong mind,and strong spirit
 - be financially stable
 - be the best god-damn engineer the world has ever seen
 - build and grow your own Buisness
 - be able to validate yourself through your actions

proposition : Do you want to
ending : '?'