paths:
  cfg_root: 'config/user_data/'  
  data: 'config/user_data/data.csv'  
  img: 'config/user_data/graph.png'  
  vars_dir: 'config/user_data/public/'
  
classes:
  
  title:
    color: 'yellow'
    size: [0.2,0.2]
    font_size: 40
  
  txt:
    font_size: 28
    color: 'white'
  
  exit:
    lsize: [1,0.2]
    bsize: [0.1,1]
    bcolor: 'red'
  
  popup:
    padding: [10]
    height: 30
    space: 10 
    size: [400,200]
  
  2butn:

    layout:
      orientation: 'horizontal'
      size: [1,1]
      spacing: 10

    button:
      size: [0.5,0.8]
      font_size: 40
      rcolor: 'green'
      lcolor: 'yellow'

main:
  buttons:
    layout_size: [1, 0.2]
    size: [0.25, 1]
    font_size: 40
    cfg_color: 'yellow'
    measure_color: 'green'
  dropdown:
    height: 60
    font_size: 24
    color: 'orange'
  about:
    size: [0.05, 1]
    color: 'cyan'

cfg:
  layout: [1, 10, 5]
  text:
    explanation: 
      font_size: 28
  input:
    font_size: 20

util:
  plot:
    legend:
      font_size: 8
      loc: 'lower right'
    warning:
      font_size: 10
      opacity: 0.3
      color: 'red'
    axes:
      tick_font_size: 9
      font_size: 14

measure:
  layout: [1, 3]
  question:
    font_size: 40
    size_y: 0.5

about:
  urls:
    creditor: "https://www.linkedin.com/in/michael-lenok-4919b659/"
    theory: "https://en.wikipedia.org/wiki/Glasser's_choice_theory"
    book: "https://www.amazon.com/"
    repo: "https://github.com/lukaselsrode/projects/tree/main/total_behavioural_tracker"
    tip: "https://buy.stripe.com/aEUcN71qN6Pv9Dq6oo"
  description:
    font_size: 28