main:
  title:
    size: [0.2, 0.2]
    font_size: 45
    color: 'blue'
  buttons:
    layout_size: [1, 0.2]
    size: [0.25, 1]
    font_size: 30
    cfg_color: 'yellow'
    measure_color: 'green'
  dropdown:
    var_height: 60
    var_font_size: 18
    var_button_color: 'orange'
  about:
    size: [0.05, 1]
    color: 'cyan'
  popup:
    size: [400, 200]

cfg:
  grid_layout: [1, 10, 5]
  text:
    var: [40, 'yellow']
    explanation: [28, 'white']
  buttons:
    height: 80
    font_size: 30
    accept_color: 'green'
    load_color: 'blue'
  input:
    font_size: 18
  popup:
    size: [400, 200]

util:
  paths:
    cfg_root: 'config/user_data/'  
    data: 'config/user_data/data.csv'  
    img: 'config/user_data/graph.png'  
    vars_dir: 'config/user_data/public/'
  axes_font_size: 13

measure:
  page_layout: [1, 3]
  question:
    font_size: 40
    size_y: 0.5
  buttons:
    font_size: 30
    size: [0.5, 0.25]
    space: 50
    no_color: 'orange'
    yes_color: 'green'

about:
  urls:
    creditor: "https://www.linkedin.com/in/michael-lenok-4919b659/"
    theory: "https://en.wikipedia.org/wiki/Glasser's_choice_theory"
    book: "https://www.amazon.com/"
    repo: "https://github.com/lukaselsrode/projects/tree/main/total_behavioural_tracker"
    tip: "https://buy.stripe.com/aEUcN71qN6Pv9Dq6oo"
  title:
    size: [0.1, 0.1]
    font_size: 40
  description:
    font_size: 24
  buttons:
    size: [1, 0.25]
    spacing: 10
    font_size: 30
    support_color: 'green'
    contribute_color: 'cyan'