paths:
  cfg_root: 'config/user_data/'  
  data: 'config/user_data/data.csv'  
  img: 'config/user_data/graph.png'  
  vars_dir: 'config/user_data/public/'
  
classes:
  title:
    color: 'yellow'
    size: [0.2,0.2]
    font_size: 40
  txt:
    font_size: 28
    color: 'white'
  exit:
    lsize: [1,0.1]
    bsize: [0.1,1]
    bcolor: 'red'
  popup:
    padding: [10]
    height: 30
    space: 10 
    size: [400,200]



main:
  title:
    size: [0.2, 0.2]
    font_size: 60
    color: 'blue'
  buttons:
    layout_size: [1, 0.2]
    size: [0.25, 1]
    font_size: 40
    cfg_color: 'yellow'
    measure_color: 'green'
  dropdown:
    height: 60
    font_size: 24
    color: 'orange'
  about:
    size: [0.05, 1]
    color: 'cyan'
  popup:
    size: [400, 200]

cfg:
  layout: [1, 10, 5]
  text:
    var: [40, 'yellow']
    explanation: [28, 'white']
  buttons:
    height: 80
    font_size: 40
    accept_color: 'green'
    load_color: 'yellow'
  input:
    font_size: 20
  popup:
    size: [400, 200]

util:
  axes_font_size: 13

measure:
  layout: [1, 3]
  question:
    font_size: 40
    size_y: 0.5
  buttons:
    font_size: 40
    size: [0.5, 0.25]
    space: 10
    no_color: 'yellow'
    yes_color: 'green'

about:
  urls:
    creditor: "https://www.linkedin.com/in/michael-lenok-4919b659/"
    theory: "https://en.wikipedia.org/wiki/Glasser's_choice_theory"
    book: "https://www.amazon.com/"
    repo: "https://github.com/lukaselsrode/projects/tree/main/total_behavioural_tracker"
    tip: "https://buy.stripe.com/aEUcN71qN6Pv9Dq6oo"
  title:
    size: [0.1, 0.1]
    font_size: 40
  description:
    font_size: 28
  buttons:
    size: [1, 0.25]
    spacing: 10
    font_size: 40
    support_color: 'yellow'
    contribute_color: 'green'