restrictions:
 - doing IOP 
 - residing in sober living   
 - taking your vivitrol shots 
 - going to meetings

boundries: 
 - having no contact with dealers
 - not agreeing to things I don't want to do
 - keeping contact with parents purpousful

rellapse: 
 - not picked up drugs
 - not fantasized about using 
 - not planned how to get away with using 
 
accountability:
 - not letting people get under your skin
 - not caring about what others perceptions are of me
 - not bieng bored 
 - not feeling hopeless
 - not isolating 
 - not taking on too much at once