values: 
  - Creativity
  - Honesty
  - Productivity

daily: 
  - Editing 
  - Studying for Bar 
  - Creating
  - Advancing Proffesionally
  - Learning 

fellowship:
  - AA
  - Sponsor 

accomplishments:
  - Was honest about cravings
  - Got proffesional path forward 
  - Got myself help when I knew I needed it