values: 
  - Truth
  - Courage
  - Innovation
  - Nature

daily: 
  - Exercing 
  - Writing 
  - Creating
  - Advancing Proffesionally
  - Learning 
  - Communing with Nature

fellowship:
  - NA
  - Sports 
  - Tech/Engineering
  - Volenteering

accomplishments:
  - Stood up against 3 people using in rehab
  - Walked away from a relationship without using 
  - Got myself help when I knew I needed it