desires:
 - be motivated
 - be focused
 - be proffesionally successful
 - let go of your ego
 - implement a program 
 - be fulfilled
 - be finacially independent 
 - be empathetic
 - be able to validate yourself through your actions

proposition : Do you want to
ending : '?'