restrictions:
 - doing IOP 
 - residing in sober living   
 - having no emotionally envolved relationships 
 - making sure you're in bed by 10:30PM 
 - not frequenting spaces with drug or alcohol use

boundries: 
 - removing threats to sobriety from my life
 - not accepting any form of bellitelment
 - having clear expectations in all proffesional relationships
 - working only during working hours - except emergencies
 - not feeling the need to change yourself

rellapse: 
 - not run out of CNS-stimulats before your perscription is refilled
 - not taken any mood altering compound without explicit medical instruction

accountability:
 - not letting people get under your skin
 - not following others instead of your gut
 - not self-loathing 
 - not hating the world
 - not isolating 
 - not believing the world revolves around you
 - not thinking you should rule the world
