Accountability:
  default:
  - not letting people get under your skin
  - not self-loathing
  - not isolating
  - not thinking of ways to get away with things
  ex: Feelings and emotional states that indicate you are actively staving off bad-behavior
    from occurring
  user: []
Boundaries:
  default:
  - Not going to bars or clubs
  - Keeping contact with family members purposeful
  - Getting to sleep by 10:00 PM
  ex: Personal boundaries which allow you to not put yourself in a situation where
    you typically would act out on 'bad behavior'
  user: []
Relapse:
  default:
  - Taking mood-altering substances
  - Drinking alcohol
  - Fighting
  - Sexual Promiscuity
  ex: What you would define as a 'relapse', either behaviorally or substance consumption
    wise
  user: []
Restrictions:
  default:
  - On probation
  - Mandatory court ordered drug testing
  - Loosing custody of children
  ex: Things that prevent you from acting out on 'bad behavior'
  user: []