Accountability:
  default:
  - not letting people get under your skin
  - not thinking you are better than others
  - not self-loathing
  - not isolating
  ex: Feelings and emotional states that indicate you are actively staving off bad-behavior
    from occurring
  user:
  - not letting people get under your skin
  - not following others
  - not thinking you are better than others
  - not thinking you should rule the world
  - not isolating
  - not hating the world
Boundaries:
  default:
  - Not going to bars or clubs
  - Keeping contact with family members purposeful
  - Getting to sleep by 10:00 PM
  ex: Personal boundaries which allow you to not put yourself in a situation where
    you typically would act out on 'bad behavior'
  user:
  - not accepting any form of belittlement
  - having clear expectations in all professional relationships
  - working only during work hours
  - getting to sleep by 10:30 pm
  - not feeling the need to change yourself
  - not hanging out in large groups of people
Relapse:
  default:
  - Taking mood-altering substances
  - Drinking alcohol
  - Fighting
  - Sexual Promiscuity
  ex: What you would define as a 'relapse', either behaviorally or substance consumption
    wise
  user:
  - not run out of cns-stimulants before prescription is refilled
  - not taken any mood altering compounds without medical instruction
  - not started cruising for sex
Restrictions:
  default:
  - On probation
  - Mandatory court ordered drug testing
  - Loosing custody of children
  ex: Things that prevent you from acting out on 'bad behavior'
  user:
  - residing in sober-living
  - doing outpatient therapy
  - having no emotionally involved relationships
  - not frequenting spaces with drug and alcohol use
  - not playing video-games during work hours
  - not ordering in food
  - not eating junk food
