Addiction:
  default:
  - sex
  - cocaine
  - alcohol
  - gambling
  - nicotine
  - risk
  - meth
  - shopping
  ex: Addictions that you have to a substance, behavior, or event
  user: []
Mental:
  default:
  - ADHD
  - Borderline Personality Disorder
  - OCD
  - Social Anxiety
  - Depression
  ex: Mental health conditions that contribute to acting out on 'bad behavior'
  user: []