Daily:
  default:
  - Exercising
  - Journaling
  - Making Art
  - Advancing Professionally
  - Learning
  ex: Daily activities you enjoy that contribute to your greater sense of purpose
  user: []
Fellowship:
  default:
  - NA
  - Sports
  - Tech/Engineering
  - Volunteering
  ex: Communities you enjoy being a part of that foster a greater sense of connection
    and meaning
  user: []
Values:
  default:
  - Truth
  - Courage
  - Intelligence
  - Openness
  - Nature
  ex: Your core values you want to live and stand by
  user: []