daily:
  default:
  - Exercising
  - Journaling
  - Making Art
  - Advancing Professionally
  - Learning
  ex: Daily activities you enjoy that contribute to your greater sense of purpose
  user:
  - exercising
  - journaling
  - organizing
  - creating
  - advancing professionally
  - learning
  - communing with nature
fellowship:
  default:
  - NA
  - Sports
  - Tech/Engineering
  - Volunteering
  ex: Communities you enjoy being a part of that foster a greater sense of connection
    and meaning
  user:
  - NA
  - Sports
  - Tech/Engineering
  - Volunteering
values:
  default:
  - Truth
  - Courage
  - Intelligence
  - Openness
  - Nature
  ex: Your core values you want to live and stand by
  user:
  - Truth
  - Courage
  - Innovation
  - Nature