Desires:
  default:
  - be clear and sharp between the ears
  - have healthier personal and professional relationships
  - be financially independent
  - be a dependable sibling, partner, parent, and employee
  ex: Your motivators, both internal and external, short and long term.
  user: []
  